library(wordcloud)
library(caTools)
library(e1071)
library(rpart)
library(rpart.plot)
library(randomForest)
library(stringr)
library(twitteR)
library(plyr)
library(tm)
library(SnowballC)
library(ggplot2)

result <- score.sentiment(tweets$text, pos.words, neg.words)
tweets$score <- result$score
tweets <- cbind(tweets,tweets$score)
write.csv(tweets, "collected_tweets.csv")
tweets$Negative <- as.factor(tweets$score<=-1)
table(tweets$Negative)
